// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jedynsvluntfgbikakfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZHluc3ZsdW50ZmdiaWtha2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTA1MzQsImV4cCI6MjA3MTQ4NjUzNH0.bZtaE2ZGSP988HtoaVzYoqvmp8VNK3FzeeYrAkYMHhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});